const container = document.getElementById("containerID");//#container

const div = document.createElement("div");
div.className = "grid";
container.appendChild(div);
const div2 = document.createElement("div");
div2.className = "grid";
container.appendChild(div2);
const div3 = document.createElement("div");
div3.className = "grid";
container.appendChild(div3);
const div4 = document.createElement("div");
div4.className = "grid";
container.appendChild(div4);
const div5 = document.createElement("div");
div5.className = "grid";
container.appendChild(div5);
const div6 = document.createElement("div");
div6.className = "grid";
container.appendChild(div6);
const div7 = document.createElement("div");
div7.className = "grid";
container.appendChild(div7);
const div8 = document.createElement("div");
div8.className = "grid";
container.appendChild(div8);
const div9 = document.createElement("div");
div9.className = "grid";
container.appendChild(div9);
const div10 = document.createElement("div");
div10.className = "grid";
container.appendChild(div10);
const div11 = document.createElement("div");
div11.className = "grid";
container.appendChild(div11);
const div12 = document.createElement("div");
div12.className = "grid";
container.appendChild(div12);
const div13 = document.createElement("div");
div13.className = "grid";
container.appendChild(div13);
const div14 = document.createElement("div");
div14.className = "grid";
container.appendChild(div14);
const div15 = document.createElement("div");
div15.className = "grid";
container.appendChild(div15);
const div16 = document.createElement("div");
div16.className = "grid";
container.appendChild(div16);

// div.style.color = "blue";
// div2.style.color = "blue";
// div3.style.color = "blue";
// div4.style.color = "blue";
// div5.style.color = "blue";
// div6.style.color = "blue";
// div7.style.color = "blue";
// div8.style.color = "blue";
// div9.style.color = "blue";
// div10.style.color = "blue";
// div11.style.color = "blue";
// div12.style.color = "blue";
// div13.style.color = "blue";
// div14.style.color = "blue";
// div15.style.color = "blue";
// div16.style.color = "blue";

// div.classList.add("grid");
// div2.classList.add("grid");
// div3.classList.add("grid");
// div4.classList.add("grid");
// div5.classList.add("grid");
// div6.classList.add("grid");
// div7.classList.add("grid");
// div8.classList.add("grid");
// div9.classList.add("grid");
// div10.classList.add("grid");
// div11.classList.add("grid");
// div12.classList.add("grid");
// div13.classList.add("grid");
// div14.classList.add("grid");
// div15.classList.add("grid");
// div16.classList.add("grid");


